/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package railreservationsystem;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author USER
 */
public class BuyTicket extends javax.swing.JFrame {

    Ticket[] ticket;
    String [] codeArray;
    int size;
    String codeF;
    String dateF;
    String originF;
    String destinationF;
    String departureF;
    String arrivalF;
    String durationF;
    double pPlatinumF;
    double pGoldF;
    
    public BuyTicket() {
        initComponents();
        
        
        size = 0;
        try
        {
            FileReader fileIn = new FileReader("Schedules.txt");
            Scanner input = new Scanner(fileIn);
            while(input.hasNextLine())
            {
                size++;
                input.nextLine();
            }
            input.close();
        }
        
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
        
        ticket = new Ticket[size];
        codeArray = new String[size];
        readFileTicket();
        
        jComboBoxTrainCode.setModel(new javax.swing.DefaultComboBoxModel<>(codeArray));
        jComboBoxTrainCode.setSelectedIndex(0);
    }
    
    public BuyTicket(String showName){
        initComponents();
        jLabelName.setText(showName);
    }
    
    public void readFileTicket()
    {
        try {
            try (FileReader readSchedule = new FileReader("Schedules.txt")) {
                BufferedReader br = new BufferedReader(readSchedule);
                
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                
                String input; int i = 0;
                while((input = br.readLine() ) != null)
                {
                    StringTokenizer st = new StringTokenizer (input,";");
                    
                    String code = st.nextToken();
                    codeArray[i] = code;
                    String date = st.nextToken();
                    String origin = st.nextToken();
                    String destination = st.nextToken();
                    String departure = st.nextToken();
                    String arrival = st.nextToken();
                    String duration = st.nextToken();
                    double pPlatinum = Double.parseDouble(st.nextToken());
                    double pGold = Double.parseDouble(st.nextToken());
                    
                    ticket[i] = new Ticket(code, date, origin, destination, departure, arrival, duration, pPlatinum, pGold);
                    Object[] tkt = {code, date, origin, destination, departure, arrival, duration, pPlatinum, pGold};
                    model.addRow(tkt);
                    
                    i++;
                    
                }
                readSchedule.close();
                }
            }
        catch (FileNotFoundException ex) {
            Logger.getLogger(BuyTicket.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BuyTicket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        ChooseSeatButton = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        jComboBoxTrainCode = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("BUY TICKET");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Date", "Origin", "Destination", "Departure", "Arrival", "Duration", "Fare Platinum", "Fare Gold"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Choose Ticket Code ");

        ChooseSeatButton.setText("Choose Seat");
        ChooseSeatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseSeatButtonActionPerformed(evt);
            }
        });

        jComboBoxTrainCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTrainCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTrainCode, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ChooseSeatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ChooseSeatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTrainCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChooseSeatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseSeatButtonActionPerformed
        new SeatingPage().setVisible(true);
    }//GEN-LAST:event_ChooseSeatButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void jComboBoxTrainCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTrainCodeActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jComboBoxTrainCode.getSelectedIndex();
        
        for(int i=0; i<size; i++)
        {
            try
            {
                PrintWriter out = new PrintWriter("CurrentSchedules.txt");
                out.print(ticket[selectedIndex].getCode()+";");
                out.print(ticket[selectedIndex].getDate()+";");
                out.print(ticket[selectedIndex].getOrigin()+";");
                out.print(ticket[selectedIndex].getDestination()+";");
                out.print(ticket[selectedIndex].getDeparture()+";");
                out.print(ticket[selectedIndex].getArrival()+";");
                out.print(ticket[selectedIndex].getDuration()+";");
                out.print(ticket[selectedIndex].getpPlatinum()+";");
                out.print(ticket[selectedIndex].getpGold()+";");
                
                out.close();
            }
            catch(FileNotFoundException e){
            System.out.print(e.toString());}
            catch(NumberFormatException e){
            System.out.print(e.toString());}
            catch(IOException e){
            System.out.print(e.toString());}
        }
    }//GEN-LAST:event_jComboBoxTrainCodeActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChooseSeatButton;
    private javax.swing.JComboBox<String> jComboBoxTrainCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
