/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package railreservationsystem;

import java.io.*;
import java.util.Scanner;
import java.util.StringTokenizer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Intel i5
 */
public class HistoryPage extends javax.swing.JFrame {

    /**
     * Creates new form HistoryPage
     */
    public HistoryPage() {
        initComponents();
        ReadHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayTable = new javax.swing.JTable();
        Origin = new javax.swing.JTextField();
        Date = new javax.swing.JTextField();
        Time = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        Seat = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Depart = new javax.swing.JTextPane();
        DisplayDepart = new javax.swing.JTextField();
        DisplayOrigin = new javax.swing.JTextField();
        DisplayDate = new javax.swing.JTextField();
        DisplayTime = new javax.swing.JTextField();
        DisplayPrice = new javax.swing.JTextField();
        DisplaySeat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        DisplayTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisplayTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DisplayTable);

        Origin.setText("jTextField1");

        Date.setText("jTextField1");

        Time.setText("jTextField1");

        Price.setText("jTextField1");

        Seat.setText("jTextField1");

        jScrollPane2.setViewportView(Depart);

        DisplayDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayDepartActionPerformed(evt);
            }
        });

        DisplayOrigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayOriginActionPerformed(evt);
            }
        });

        DisplayDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayDateActionPerformed(evt);
            }
        });

        DisplayTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayTimeActionPerformed(evt);
            }
        });

        DisplayPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayPriceActionPerformed(evt);
            }
        });

        DisplaySeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplaySeatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DisplayPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplayDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplayOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplayTime, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplaySeat, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Origin, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Seat, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Origin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DisplayDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(DisplayOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(DisplayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(DisplayTime, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(DisplayPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(DisplaySeat, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplayTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)DisplayTable.getModel();
        
        int selectedRow=DisplayTable.getSelectedRow();
        
        String depature = model.getValueAt(selectedRow, 0).toString();
        String origin = model.getValueAt(selectedRow, 1).toString();
        String date = model.getValueAt(selectedRow, 2).toString();
        String time = model.getValueAt(selectedRow, 3).toString();
        String price = model.getValueAt(selectedRow, 4).toString();
        //double p = Double.parseDouble(price);
        String seat = model.getValueAt(selectedRow, 5).toString();
        
        Depart.setText(depature);
        Origin.setText(origin);
        Date.setText(date);
        Time.setText(time);
        Price.setText(price);
        Seat.setText(seat);
    }//GEN-LAST:event_DisplayTableMouseClicked

    private void DisplayDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayDepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayDepartActionPerformed

    private void DisplayOriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayOriginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayOriginActionPerformed

    private void DisplayDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayDateActionPerformed

    private void DisplayTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayTimeActionPerformed

    private void DisplayPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayPriceActionPerformed

    private void DisplaySeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplaySeatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplaySeatActionPerformed

    /**
     * @param args the command line arguments
     */
    private void ReadHistory(){
        //TicketDetails cust[]=new TicketDetails[100];
        try{
            
            //String inFile="Details.txt";
            FileReader nm = new FileReader("Details.txt");
            Scanner in = new Scanner(nm);
            DefaultTableModel model=(DefaultTableModel)DisplayTable.getModel();

            StringTokenizer hs;
            String input,delims=";";

            while(in.hasNextLine()){//rt4teyy
                input = in.nextLine();    
                hs = new StringTokenizer(input,delims);

                String depature = hs.nextToken();
                String origin = hs.nextToken();
                String date = hs.nextToken();
                String time = hs.nextToken();
                String price = hs.nextToken();
                double p = Double.parseDouble(price);
                String seat = hs.nextToken();

                Object[] cust = {depature, origin, date, time, p, seat};

                model.addRow(cust);
            }
            in.close();
            nm.close();
            
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Date;
    private javax.swing.JTextPane Depart;
    private javax.swing.JTextField DisplayDate;
    private javax.swing.JTextField DisplayDepart;
    private javax.swing.JTextField DisplayOrigin;
    private javax.swing.JTextField DisplayPrice;
    private javax.swing.JTextField DisplaySeat;
    private javax.swing.JTable DisplayTable;
    private javax.swing.JTextField DisplayTime;
    private javax.swing.JTextField Origin;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField Seat;
    private javax.swing.JTextField Time;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
